import "server-only";
import listingEmbeddings from "@/data/listing-embeddings.json";
import { listings as staticListings } from "@/data/listings";
import { getListingsWithEmbeddings } from "@/lib/db/listings";
import { embedText, cosineSimilarity } from "@/lib/embeddings";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import type { Listing } from "@/types/listing";

// AI semantic search — genuinely dense-embedding based, not keyword
// matching. The query is always embedded live, at request time, with the
// local MiniLM model (src/lib/embeddings.ts). What it's compared against
// depends on whether Supabase is set up yet:
//  - configured: every listing's stored `search_embedding` column, kept
//    current by the admin create/update actions — so a listing added
//    through /admin is searchable immediately.
//  - not configured: the precomputed src/data/listing-embeddings.json,
//    generated by `npm run build:embeddings` against the static seed data.
// Either way, nothing is sent to an external API — everything runs
// in-process.

export interface SearchResult {
  listing: Listing;
  score: number;
}

const staticEmbeddingBySlug = new Map(
  listingEmbeddings.entries.map((entry) => [entry.slug, entry.embedding])
);

async function getSearchCandidates(): Promise<Array<{ listing: Listing; embedding: number[] }>> {
  if (isSupabaseConfigured) {
    const rows = await getListingsWithEmbeddings();
    return rows.filter(
      (row): row is { listing: Listing; embedding: number[] } => row.embedding !== null
    );
  }

  return staticListings
    .map((listing) => ({ listing, embedding: staticEmbeddingBySlug.get(listing.slug) }))
    .filter((row): row is { listing: Listing; embedding: number[] } => row.embedding !== undefined);
}

export async function semanticSearch(
  query: string,
  { limit = 6, minScore = 0.15 }: { limit?: number; minScore?: number } = {}
): Promise<SearchResult[]> {
  const trimmed = query.trim();
  if (!trimmed) return [];

  const [queryVector, candidates] = await Promise.all([
    embedText(trimmed),
    getSearchCandidates(),
  ]);

  const scored: SearchResult[] = [];
  for (const { listing, embedding } of candidates) {
    const score = cosineSimilarity(queryVector, embedding);
    if (score >= minScore) {
      scored.push({ listing, score });
    }
  }

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit);
}
