import type { Listing } from "@/types/listing";
import { generatedListings } from "./generated-listings";

/**
 * Seed listing data for local development and the AI search demo.
 *
 * The 8 listings below are original, freshly-written examples created for
 * this project — not copied from any live agency site. They're combined
 * with a much larger batch of procedurally varied listings (same real
 * Prime London areas, same tone, generated by scripts/generate-listings.mjs)
 * so search, filters and the grid have enough volume and variety to feel
 * like a live platform rather than a handful of curated examples. All of it
 * stands in until real Manzell listings are connected. Images throughout are
 * either generated placeholder graphics or real, free-to-use stock
 * photography reused across listings by property type / room — never a
 * photograph of a specific real property (see scripts/lib/listing-photos.mjs
 * for the sourcing note; the same ER1 ethics rationale that applies to using
 * Manzell's real listing data applies to using their real property photos).
 */
const handWrittenListings: Listing[] = [
  {
    id: "man-0001",
    slug: "eaton-place-belgravia-sw1",
    purpose: "sale",
    status: "for-sale",
    propertyType: "townhouse",
    tenure: "freehold",
    title: "A stucco-fronted townhouse on a quiet Belgravia garden square",
    addressLine: "Eaton Place",
    area: "Belgravia",
    postcodeDistrict: "SW1",
    price: 8250000,
    bedrooms: 5,
    bathrooms: 4,
    receptions: 3,
    sizeSqft: 4120,
    epcRating: "D",
    councilTaxBand: "H",
    summary:
      "Five floors of classic Belgravia proportions behind a Grade II listed façade, with private garden square access.",
    description: [
      "Set behind a pillared portico on one of Belgravia's most consistently handsome terraces, this five-storey house has been restored with a light touch — cornicing, ceiling roses and the original staircase balustrade are all intact, while the kitchen and bathrooms have been rebuilt around them.",
      "The principal reception rooms sit on the raised ground and first floors, both with the full ceiling height the terrace is known for and a pair of interconnecting doors that let them run as one room for entertaining. The lower ground floor holds an open kitchen and family room opening onto a south-facing patio.",
      "Upstairs, the principal bedroom takes the width of the house at second-floor level with a dressing room and en suite; three further bedrooms and a study occupy the third and fourth floors. Residents' access to the garden square opposite is included with the freehold.",
    ],
    features: [
      "Grade II listed stucco terrace",
      "Private garden square access",
      "South-facing lower ground floor patio",
      "Original cornicing and staircase retained",
      "Off-street parking permit eligible",
    ],
    images: [
      { src: "/photos/exterior-townhouse-01.jpg", alt: "Stock photograph illustrating a stucco-fronted townhouse exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-01.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-dining-01.jpg", alt: "Stock photograph illustrating a dining room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-01.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-study-01.jpg", alt: "Stock photograph illustrating a study of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-01.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-07-14",
    featured: true,
  },
  {
    id: "man-0002",
    slug: "mount-street-mayfair-w1",
    purpose: "sale",
    status: "for-sale",
    propertyType: "apartment",
    tenure: "share-of-freehold",
    title: "A remodelled lateral apartment above Mount Street's galleries",
    addressLine: "Mount Street",
    area: "Mayfair",
    postcodeDistrict: "W1",
    price: 5450000,
    bedrooms: 3,
    bathrooms: 3,
    receptions: 1,
    sizeSqft: 2380,
    epcRating: "C",
    councilTaxBand: "H",
    serviceChargeAnnual: 14200,
    leaseYearsRemaining: 987,
    summary:
      "A full-floor rebuild behind a red-brick Mayfair mansion block, finished to an exacting, gallery-quiet standard.",
    description: [
      "This third-floor apartment occupies the full width of a mansion block a short walk from the Connaught, and was taken back to shell during a recent renovation — the layout, services and finishes are all new, while the block's original sash windows and high ceilings were kept.",
      "A single broad reception room runs front to back, with a separate dining kitchen fitted in fumed oak and Silestone. Each of the three bedrooms has its own bathroom, and the principal suite includes a dressing room built into what was previously a fourth bedroom.",
      "A porter is on duty during the day, and the share of freehold gives the four flats in the block direct control over the building's management and any future works.",
    ],
    features: [
      "Full-floor lateral layout",
      "Comprehensive recent renovation",
      "Daytime porterage",
      "Share of freehold",
      "Three en suite bedrooms",
    ],
    images: [
      { src: "/photos/exterior-apartment-01.jpg", alt: "Stock photograph illustrating an apartment exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-02.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-02.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-02.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bathroom-01.jpg", alt: "Stock photograph illustrating a bathroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-08-02",
    featured: true,
  },
  {
    id: "man-0003",
    slug: "wilton-crescent-knightsbridge-sw1",
    purpose: "let",
    status: "to-let",
    propertyType: "apartment",
    tenure: "leasehold",
    title: "A quietly grand first-floor apartment on Wilton Crescent",
    addressLine: "Wilton Crescent",
    area: "Knightsbridge",
    postcodeDistrict: "SW1",
    rentPcm: 13500,
    bedrooms: 2,
    bathrooms: 2,
    receptions: 1,
    sizeSqft: 1640,
    epcRating: "C",
    councilTaxBand: "G",
    serviceChargeAnnual: 9800,
    leaseYearsRemaining: 74,
    summary:
      "Curved sash windows over the crescent's private gardens, let furnished or unfurnished with immediate availability.",
    description: [
      "This first-floor apartment follows the curve of Wilton Crescent itself, so the drawing room's three sash windows look directly over the private communal gardens rather than the street. The rooms keep the crescent's original proportions, with a run of storage and a separate study carved out of what would once have been a dressing room.",
      "The kitchen was updated within the last two years and opens to a small breakfast area; both bedrooms are doubles with fitted wardrobes, and the principal has an en suite finished in Bianco Carrara marble.",
      "Available on a company or private let, furnished or unfurnished, with keyholder access to the gardens included for the tenancy.",
    ],
    features: [
      "Communal garden access",
      "Furnished or unfurnished",
      "Recently updated kitchen",
      "Long lease (74 years)",
      "Available immediately",
    ],
    images: [
      { src: "/photos/exterior-apartment-02.jpg", alt: "Stock photograph illustrating an apartment exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-03.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-03.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-study-02.jpg", alt: "Stock photograph illustrating a study of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bathroom-02.jpg", alt: "Stock photograph illustrating a bathroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-08-20",
  },
  {
    id: "man-0004",
    slug: "phillimore-gardens-kensington-w8",
    purpose: "sale",
    status: "sstc",
    propertyType: "maisonette",
    tenure: "share-of-freehold",
    title: "A garden maisonette on a Phillimore Gardens plane-tree avenue",
    addressLine: "Phillimore Gardens",
    area: "Kensington",
    postcodeDistrict: "W8",
    price: 3195000,
    bedrooms: 3,
    bathrooms: 2,
    receptions: 2,
    sizeSqft: 1980,
    epcRating: "D",
    councilTaxBand: "G",
    serviceChargeAnnual: 4600,
    leaseYearsRemaining: 991,
    summary:
      "Raised ground and lower ground floors of a white stucco villa, with a private walled garden of its own.",
    description: [
      "Rather than a shared communal garden, this maisonette has sole use of a 45ft walled garden accessed directly from the lower ground floor kitchen — an unusual feature for the area and one that suits family use as much as entertaining.",
      "The raised ground floor holds a double reception room with the villa's original shutters and a marble fireplace at either end; two further bedrooms and a family bathroom sit on the floor below alongside the garden-facing kitchen.",
      "Phillimore Gardens sits between Holland Park and Kensington High Street, with the Design Museum and the park's tennis courts both a short walk away.",
    ],
    features: [
      "Private walled garden",
      "Two reception rooms",
      "Original shutters and fireplaces",
      "Moments from Holland Park",
    ],
    images: [
      { src: "/photos/exterior-maisonette-01.jpg", alt: "Stock photograph illustrating a maisonette exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-04.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-04.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-03.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bathroom-03.jpg", alt: "Stock photograph illustrating a bathroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-06-30",
  },
  {
    id: "man-0005",
    slug: "chepstow-villas-notting-hill-w11",
    purpose: "sale",
    status: "for-sale",
    propertyType: "detached-house",
    tenure: "freehold",
    title: "A detached villa on Chepstow Villas with off-street parking",
    addressLine: "Chepstow Villas",
    area: "Notting Hill",
    postcodeDistrict: "W11",
    price: 11500000,
    bedrooms: 6,
    bathrooms: 5,
    receptions: 3,
    sizeSqft: 5460,
    epcRating: "D",
    councilTaxBand: "H",
    summary:
      "A rare fully detached house on Notting Hill's grandest villa road, with a garden, garage and lower ground leisure floor.",
    description: [
      "Detached houses are unusual on Chepstow Villas, where most of the road's Italianate villas are semi-detached at best — this one stands alone behind wrought-iron gates, with off-street parking for two cars and an integral garage.",
      "Formal reception rooms occupy the ground floor, with a study and a family kitchen extending into the garden at the rear. The lower ground floor has been fitted out as a leisure floor with a media room and a small gym, and the top two floors hold six bedrooms across a mix of family and staff-style configurations.",
      "Westbourne Grove's restaurants and Portobello Market are both within ten minutes on foot.",
    ],
    features: [
      "Fully detached",
      "Off-street parking and garage",
      "Lower ground leisure floor",
      "Private rear garden",
      "Six bedrooms",
    ],
    images: [
      { src: "/photos/exterior-detached-house-01.jpg", alt: "Stock photograph illustrating a detached house exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-05.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-dining-02.jpg", alt: "Stock photograph illustrating a dining room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-05.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-04.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
      { src: "/photos/interior-hallway-01.jpg", alt: "Stock photograph illustrating an entrance hallway of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-05-18",
    featured: true,
  },
  {
    id: "man-0006",
    slug: "chester-row-belgravia-sw1",
    purpose: "let",
    status: "let-agreed",
    propertyType: "mews-house",
    tenure: "leasehold",
    title: "A cobbled mews house off Chester Row",
    addressLine: "Studio Mews, off Chester Row",
    area: "Belgravia",
    postcodeDistrict: "SW1",
    rentPcm: 7250,
    bedrooms: 2,
    bathrooms: 2,
    receptions: 1,
    sizeSqft: 1150,
    epcRating: "C",
    councilTaxBand: "F",
    leaseYearsRemaining: 58,
    summary:
      "A garaged mews house on a cobbled Belgravia lane, arranged over three compact, well-lit floors.",
    description: [
      "Tucked away on one of the small cobbled mews between Chester Row and Ebury Street, this house keeps its garage at street level and lives upward — a kitchen and dining room on the first floor, a double bedroom with en suite above, and a second bedroom and roof terrace on the top floor.",
      "The scale is intimate rather than grand, which is the appeal of mews houses in this pocket of Belgravia: quiet, self-contained, and a five-minute walk from Sloane Square.",
    ],
    features: [
      "Integral garage",
      "Roof terrace",
      "Cobbled mews setting",
      "Five minutes to Sloane Square",
    ],
    images: [
      { src: "/photos/exterior-mews-house-02.jpg", alt: "Stock photograph illustrating a mews house exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-01.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-02.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-02.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-07-01",
  },
  {
    id: "man-0007",
    slug: "harley-street-marylebone-w1",
    purpose: "let",
    status: "to-let",
    propertyType: "penthouse",
    tenure: "leasehold",
    title: "A penthouse with a private roof terrace near Harley Street",
    addressLine: "Harley Street",
    area: "Marylebone",
    postcodeDistrict: "W1",
    rentPcm: 9800,
    bedrooms: 2,
    bathrooms: 2,
    receptions: 1,
    sizeSqft: 1420,
    epcRating: "B",
    councilTaxBand: "G",
    serviceChargeAnnual: 6100,
    leaseYearsRemaining: 132,
    summary:
      "A top-floor apartment with lift access and a wraparound terrace, finished within the last three years.",
    description: [
      "This penthouse sits on the top floor of a converted Georgian townhouse with a discreet lift, and was reconfigured within the last three years to open the kitchen into the main reception room and add a wraparound terrace across the rear of the building.",
      "Both bedrooms are doubles with fitted storage, and the principal opens directly onto the terrace. Marylebone High Street's shops and cafés are two minutes away on foot, with Regent's Park a short walk beyond.",
    ],
    features: [
      "Private wraparound roof terrace",
      "Lift access",
      "Recently reconfigured open-plan layout",
      "Two minutes to Marylebone High Street",
    ],
    images: [
      { src: "/photos/exterior-penthouse-01.jpg", alt: "Stock photograph illustrating a penthouse exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-03.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-03.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-03.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bathroom-04.jpg", alt: "Stock photograph illustrating a bathroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-08-25",
  },
  {
    id: "man-0008",
    slug: "cheyne-walk-chelsea-sw3",
    purpose: "sale",
    status: "under-offer",
    propertyType: "apartment",
    tenure: "share-of-freehold",
    title: "A riverside apartment overlooking the Thames on Cheyne Walk",
    addressLine: "Cheyne Walk",
    area: "Chelsea",
    postcodeDistrict: "SW3",
    price: 4750000,
    bedrooms: 3,
    bathrooms: 2,
    receptions: 1,
    sizeSqft: 2010,
    epcRating: "D",
    councilTaxBand: "H",
    serviceChargeAnnual: 8900,
    leaseYearsRemaining: 989,
    summary:
      "Second-floor river views along one of Chelsea's most storied stretches of embankment.",
    description: [
      "Cheyne Walk's river frontage has drawn painters and writers for two centuries, and this second-floor apartment takes in the Thames along almost its full width from a run of three windows in the reception room.",
      "The apartment has been kept close to its original 1930s layout — generous room sizes, a separate dining room, and a kitchen positioned to the rear away from the river-facing rooms — with bathrooms and services updated more recently.",
      "Albert Bridge and the Chelsea Physic Garden are both within a few minutes' walk.",
    ],
    features: [
      "Uninterrupted river views",
      "Separate dining room",
      "Share of freehold",
      "Moments from Albert Bridge",
    ],
    images: [
      { src: "/photos/exterior-apartment-01.jpg", alt: "Stock photograph illustrating an apartment exterior of this style — not a photograph of this specific property." },
      { src: "/photos/interior-livingroom-04.jpg", alt: "Stock photograph illustrating a reception room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-dining-03.jpg", alt: "Stock photograph illustrating a dining room of this style — not a photograph of this specific property." },
      { src: "/photos/interior-kitchen-04.jpg", alt: "Stock photograph illustrating a kitchen of this style — not a photograph of this specific property." },
      { src: "/photos/interior-bedroom-04.jpg", alt: "Stock photograph illustrating a bedroom of this style — not a photograph of this specific property." },
    ],
    dateListed: "2026-06-05",
  },
];

export const listings: Listing[] = [...handWrittenListings, ...generatedListings];

export function getListingBySlug(slug: string): Listing | undefined {
  return listings.find((listing) => listing.slug === slug);
}

export function getFeaturedListings(): Listing[] {
  return listings.filter((listing) => listing.featured);
}

export function getListingsByPurpose(purpose: Listing["purpose"]): Listing[] {
  return listings.filter((listing) => listing.purpose === purpose);
}
